#!/usr/bin/perl -w
# $Id: test_ssv,v 1.2 2001/08/01 02:15:03 christopher Exp $

use CSV;

local $CSV::Delimiters = ";";
while (<DATA>) {
    print join(":", CSVsplit($_)), "\n";
}

__DATA__
This is;a very normal;123 5th St.;record
Only;a little more;difficult;
"One from FAQ will do";"sec""ond"
"But; not";"3rd""";"or";"""fifth"
"don't";"forget";"fourth"";""";"and"  ;  """;""sixth".
"Of course; it doesn't solve";everything;8;N;1
"Is there a new emacs   perl-mode?"
"Tom";"tom@fiction.org"
Empty fields needed;;"and "wanted

Some;"";boundary  ";cases"";  ;too
Grok this\; Spok!
"Didn't you notice\! in it \{the spec\}"
"Multi-
line";test
